accounts/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views


app_name='accounts'
urlpatterns = [
    # path('',views.user_login,name="user-login"),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/',auth_views.LogoutView.as_view(),name="logout"),
    # path('password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    # path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),

    path('dashboard/',views.dashboard,name="dashboard"),
    path('',include('django.contrib.auth.urls')),
    path('register/',views.user_registration,name="user_registration"),
    path('edit/',views.edit,name="edit"),
    

]

conshare/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls'),name='post'),
    path('accounts/', include('accounts.urls'),name='accounts'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name='post'
urlpatterns = [
    # path('',views.user_login,name="user-login"),

]

accounts/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    date_of_birth = models.DateTimeField(blank=True,null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self):
        return f'Profile for user{self.user.username}'

post/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify

# Create your models here.

class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='image_created',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    description = models.TextField(blank=True)
    img = models.ImageField(upload_to='images/%Y/%m/%d/')
    url = models.URLField()
    created = models.DateTimeField(auto_now_add=True,db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name="images_liked",blank=True)

    def __str__(self):
        return self.title

    def save(self,*args,**kwargs):
        #automatically generate the slug when no slug is provided
        if not self.slug:
            self.slug = slugify(self.title)
            super().save(*args,**kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class LoginForm(forms.Form):
        username = forms.CharField()
        password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
        password = forms.CharField(label='Password',widget=forms.PasswordInput)
        password2 = forms.CharField(label='Repeat Password',widget=forms.PasswordInput)

        class Meta:
                model = User
                fields = ('username','first_name','email')

        def clean_password2(self):
                cd = self.cleaned_data
                if cd['password'] !=cd['password2']:
                        raise forms.ValidationError('Passwords do not match!')
                return cd['password2']

class UserEditForm(forms.ModelForm):
        class Meta:
                model = User
                fields = ['first_name','last_name','email']

class ProfileEditForm(forms.ModelForm):
        class Meta:
                model = Profile
                fields = ['date_of_birth','photo']

post/forms.py
from django import forms
from .models import Image

class ImageCreateForms(forms.ModelForm):
    class Meta:
        model = Image
        fields=['title','url','description']
        widgets = {'url':forms.HiddenInput}

    def clean_url(self):
        url = forms.cleaned_data['url']
        valid_extensions = ['jpeg', 'jpg','png']
        extension = url.rsplit('.',1)[1].lower()

        if extension not in valid_extensions:
            raise forms.ValidationError("The given url does not match valid image extensions")
        return url

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login
from django.http import HttpResponse
from .forms import LoginForm,UserRegistrationForm,ProfileEditForm,UserEditForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def user_login(request):
    if request.method == 'POST':
        #form is submitted
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user= authenticate(request, password='password', username='username')

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('User Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid Login')
        
    else:
        form = LoginForm()
    return render(request,'accounts/login.html',{'form':form})

@login_required
def dashboard(request):
    return render(request,'accounts/dashboard.html',{'section':'dashboard'})

def user_registration(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            #set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()

            return render(request,'accounts/register_done.html',{'new_user':new_user})

    else:
        user_form = UserRegistrationForm()
    return render(request,'accounts/register.html',{'user_form':user_form})

@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance = request.user,data=request.POST)
        profile_form = ProfileEditForm(instance =request.user.profile,data=request.POST,files = request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
    else:
        user_form = UserEditForm(instance = request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request,'accounts/edit.html',{'user_form':user_form,'profile_form':profile_form})

post/views.py
from django.shortcuts import render


# Create your views here.

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title%}{% endblock%}</title>
    {% comment %} <link rel="stylesheet" type="text/css" href=" {% static '/css/base.css' %} "> {% endcomment %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    
</head>
<body>
    <div id="header">
        <span class="logo">Conshare</span>
        {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == "dashboard" %}class="selected"{% endif %}>
                    <a href="{% url "accounts:dashboard" %}">Dashboard</a>
                </li>
                <li {% if section == "images" %}class="selected"{% endif %}>
                    <a href="#">Images</a>
                </li>
                <li {% if section == "people" %}class="selected"{% endif %}>
                    <a href="#">People</a>
                </li>
            </ul>
        {% endif %}
        <span class="user">
            {% if request.user.is_authenticated %}
            Hello {{ request.user.first_name }},
                <a href="{% url "accounts:logout" %}">Logout</a>
            {% else %}
                <a href="{% url "accounts:login" %}">Log-in</a>
            {% endif %}
        </span>
    </div>
    <div id="content">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li class="{{message.tags}}">
                    {{message|safe}}
                    <a href="#" class="close">x</a>
                {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>
</body>
</head>

accounts/templates/accounts/dashboard.html
{% extends "accounts/base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}

<h1>Dashboard</h1>
<p>Welcome to your dashboard.You can <a href="{% url 'accounts:edit'%}">edit your account</a></p>
{% endblock %}

accounts/templates/accounts/edit.html
{% extends 'accounts/base.html'%}
{% block title%} Edit your Account {% endblock %}

{% block content%}
    <h1>Edit your account</h1>
    <p>You can edit your account using the following form:</p>
    <form method="post" enctype="multipart/form-data">
        {{user_form.as_p}}
        {{profile_form.as_p}}
        {% csrf_token %}
        <p><input type="submit" value="Save Changes"></p>
    </form>
{% endblock content%}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html'%}

{% block title%} Create an account {% endblock%}

{% block content%}
    <h1>Create an Account</h1>
    <p>PLease, sign up using the following form:</p>
    <form method="post">
        {{user_form.as_p}}
        {%csrf_token%}
        <p> <input type="submit" value="create my account"></p>
    </form>
{% endblock%}

accounts/templates/accounts/register_done.html
{% extends 'accounts/base.html'%}

{% block title%}Welcome{% endblock%}

{% block content%}
    <h1>Welcome {{new_user.first_name}}!</h1>
    <p>Your account has been successf ully created. You can now <a href="{% url 'accounts:login'%}">Log in</a></p>
{% endblock%}

post/templates/post/base.html
Heloo

post/templates/post/login.html
world